### ISSUE TITLE
Error : Callback not provided on API call

### ISSUE THREAD

**Issue by user1702** [andreareginato/simple-oauth2#11]
Hi, I am using Client Credentials flow where an error is thrown "Callback not provided on API call"
 var credentials = {
                clientID: credentialObj.ClientId,
                clientSecret: credentialObj.ClientSecret,
                site: 'http://localhost:3000/',
                tokenPath: 'oauth/token'
            };
            // Initialize the OAuth2 Library
            var OAuth2 = require('simple-oauth2')(credentials);
            // Get the access token object for the client
            OAuth2.Client.getToken(saveToken);

**Comment by jonathansamines** [comment]
I´ll close this, since it has already solved in #30.
