### ISSUE TITLE
Expose proxy options of request package

### ISSUE THREAD

**Issue by atrniv** [andreareginato/simple-oauth2#16]
Hi, I'm trying to use the simple-oauth2 client from behind a squid proxy and i need to be able to set the proxy option on the request module. It would be great if you could expose it somehow on the simple-oauth2 package.

**Comment by jonathansamines** [comment]
Since it hasn´t been requested again, i will close this. Feel free to open it again if it is still an issue.

**Comment by siboulet** [comment]
You can use the `http` option to pass  [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent) as `agent` to the internal http library used by simple-oauth2 (wreck).

```js
const HttpsProxyAgent = require('https-proxy-agent');

let oauth = OAuth2.create({
  client: {
  },
  auth: {
  },
  http: {
    agent: new HttpsProxyAgent('http://127.0.0.1:8888'),
  },
});
