### ISSUE TITLE
Adding Response Status Code in body

### ISSUE THREAD

**Issue by tomalex0** [andreareginato/simple-oauth2#28]
The body i'm getting as part of  request  doesn't have any status code, just the text notations like
`{ error: 'invalid_access', error_description: 'Auth code is invalid or expired.' }`. even though the status code is `400`. It  would have been good if body also have reference to statusCode. 

### Right Now
https://github.com/andreareginato/simple-oauth2/blob/master/lib/core.js#L87
```
if (response.statusCode >= 400) return callback(body || new errors.HTTPError(response.statusCode), null)
```

### What to be done
This is just a draft, conditions and naming need to be changed accordingly
```
if (response.statusCode >= 400) {
    body.responsecode = new errors.HTTPError(response.statusCode);
    return callback(body || new errors.HTTPError(response.statusCode), null);
}
```

Let me know your thoughts

**Comment by jonathansamines** [comment]
This module shouldn´t care about the response format, so we shouldn´t be modifying the original response from the OAuth2 server, since it gives us a lot of edge cases to take in account.

Do you guys think that this really has to be added?

**Comment by andreareginato** [comment]
I guess the priority is to keep a simple solution.
+1 @jonathansamines

**Comment by PuKoren** [comment]
@jonathansamines I think header response code is enough widely used

**Comment by jonathansamines** [comment]
I´ll close this issue since this transformations are out of the scope of simple-oauth2.
