### ISSUE TITLE
Missing "authorizationPath" key in express example

### ISSUE THREAD

**Issue by malek0512** [andreareginato/simple-oauth2#42]
You might want to add "authorizationPath" key to "oauth2" variable, in your express example (https://github.com/andreareginato/simple-oauth2#express-and-github-example)

**Comment by andreareginato** [comment]
@malek0512, thanks for pointing it out. Could you find the time to send us a pull request with the missing variable? That would help a lot. Thanks.

**Comment by malek0512** [comment]
Sure, no problem
