### ISSUE TITLE
Fails behind corporate proxy with v2.12.0 of request module

### ISSUE THREAD

**Issue by jwdavistx** [andreareginato/simple-oauth2#48]
Sorry that I don't have more diagnostic information, but I've found that the v2.12.0 of request that this module uses didn't seem work properly behind my corporate proxy.

After I manually updated the request module to the latest, all appears to work as intended without any code changes.

**Comment by jonathansamines** [comment]
Hi @jwdavistx to what request version did you upgraded? Do you know if this problem is specific to the **request*** module?

**Comment by jwdavistx** [comment]
Hey @jonathansamines, at the last build I had simply done request@latest but I can't recall the specific  version number.  This was maybe a couple weeks ago.  I imagine i it was 2.67.*

When I was originally looking in to the issue, it appeared that there were significant changes to the tunnel-agent usage that was used in the current targeted version of request (2.12.0). I didn't look much beyond noticing that difference, so, I couldn't say for sure if the issue was actually with tunnel-agent, or something specific to request as a whole.

In either event, as of the last build, we still had to update to the latest request library to get through the corporate proxy. No other changes, just updating that dependency within simple-oauth2.

**Comment by jonathansamines** [comment]
Hi @jwdavistx the version ```0.4.0``` was released yesterday, it updated all dependencies so ```request``` was updated also to the latest available version. Let me know if that solves your problem.

Feel free to open this again, if the problem persist after upgrading.
