### ISSUE TITLE
Fix development model

### ISSUE THREAD

**Issue by jonathansamines** [andreareginato/simple-oauth2#50]
Currently, there isn´t any way to track npm version against the actual repository code. Also the development branch is broken. In order to have better version tracking, i will implement some changes in the way this repository works. The changes are the following:

 - The development branch will be fixed and renamed to "develop"
 - Master always will be deployable (it will point to the latest version of the npm published version)
 - Every pull request should be made against the development branch and will be merged into that branch. Then a project maintainer will merge a set of changes to master.
 - For every npm release a git tag will be created, so we can easily track a package version.

And thats is for now, i hope this changes improves the project maintainability.

**Comment by andreareginato** [comment]
+1

**Comment by jonathansamines** [comment]
Finished!
* The development branch was fixed, and now is in sync with master.
* The new version was pushed to the NPM registry (v0.3.0), and a tag was created on this repository. Master and develop were updated with the latest changes.
* Documentation updated to reflect the API changes.

**Comment by andreareginato** [comment]
Great job.

Il giorno dom 29 nov 2015, 18:41 Jonathan Samines <notifications@github.com>
ha scritto:
