### ISSUE TITLE
OAuth token submitted with the request can not be parsed

### ISSUE THREAD

**Issue by vin14976** [andreareginato/simple-oauth2#53]
Hi,
I'm using this library along with "node-outlook" to invoke O365 APIs.

var credentials = {
    clientID: "xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx",
    clientSecret: "xxxxxxxxxxxxxxxxxxxxxx",
    site: "https://login.microsoftonline.com/common",
    authorizationPath: "/oauth2/v2.0/authorize",
    tokenPath: "/oauth2/v2.0/token"
}
var scopes = [
    "openid",
    "offline_access",
    "https://outlook.office.com/mail.read",
    "https://outlook.office.com/calendars.read",
    "https://outlook.office.com/contacts.read",
];

I've got tokens,
vin14976@hotmail.com = Token
 access_token = "..."
 expires_at = Mon Dec 14 2015 06:28:00 GMT+0530 (India Standard Time)
 expires_in = "3600"
 id_token = "..."
 id_token_expires_in = "86400"
 refresh_token = "..."
 scope = "https://outlook.office.com/mail.read https://outlook.office.com/calendars.read https://outlook.office.com/contacts.read"
 token_type = "Bearer"

But, when I invoke O365 API, using above token - I get following error in response header;

API call goes on, "https://outlook.office.com/api/v2.0/Me/Events" returned with,
 statusCode = 401
 statusMessage = "Unauthorized"

Following headers,

headers = Object
 client-request-id = "7363b30d-4af2-4607-b338-e855d85f17e7, 7363b30d-4af2-4607-b338-e855d85f17e7"
 connection = "close"
 content-length = "0"
 date = "Thu, 10 Dec 2015 04:27:33 GMT"
 request-id = "1f55bafc-e733-4af3-acf1-09045008541f"
 server = "Microsoft-IIS/8.5"
 set-cookie = Array[3]
 0 = "ClientId=WNPNIAPEG0VV3GHB6SSLG; expires=Fri, 09-Dec-2016 04:27:33 GMT; path=/; secure; HttpOnly"
 1 = "exchangecookie=c01c8d2bad8441f1b935b5c2fd363f20; expires=Sat, 10-Dec-2016 04:27:34 GMT; path=/; HttpOnly"
 2 = "ClientId=WNPNIAPEG0VV3GHB6SSLG; expires=Fri, 09-Dec-2016 04:27:33 GMT; path=/; secure; HttpOnly"
 length = 3
proto = Array[0]
 www-authenticate = "Bearer client_id="00000002-0000-0ff1-ce00-000000000000", trusted_issuers="00000001-0000-0000-c000-000000000000@*", token_types="app_asserted_user_v1 service_asserted_app_v1", authorization_uri="https://login.windows.net/common/oauth2/authorize", error="invalid_token",Basic Realm="",Basic Realm="""
 x-backendhttpstatus = "401"
 x-beserver = "SG2PR01MB0361"
 x-calculatedbetarget = "SG2PR01MB0361.apcprd01.prod.exchangelabs.com"
 x-diaginfo = "SG2PR01MB0361"
 x-ms-diagnostics = "2000001;reason="OAuth token submitted with the request can not be parsed.";error_category="invalid_token""
 x-msedge-ref = "Ref A: 229F86A986BB4BBA8ABE8AF95247707E Ref B: 003D81F0D681C4C8300EF860870246D0 Ref C: Wed Dec 09 20:27:33 2015 PST"
 x-powered-by = "ASP.NET"

Please suggest.

**Comment by jonathansamines** [comment]
Hi @vin14976 did you resolved your issue? this problems it´s unlikely to be a problem with this lib, since it´s scope it´s to get an OAuth2 token, which is actually happening.

**Comment by vin14976** [comment]
Yes, my issue is resolved. I was passing the complete token object to the service, instead of just access token.
