### ISSUE TITLE
refresh token requests that require scope

### ISSUE THREAD

**Issue by jimmyjames** [andreareginato/simple-oauth2#57]
I'm using an OAuth provider that requires a `scope` parameter when refreshing a token. The current `refresh()` implementation does not allow sending additional parameters for the request. Can `refresh()` be extended to allow passing in additional parameters?

**Comment by jonathansamines** [comment]
Hi @jimmyjames this issue was already reported and currently there is WIP for this on #49 which is still pending to merge.

**Comment by jonathansamines** [comment]
The version ```0.4.0``` was released yesterday, which should solve this problem. Let me know if that solves your problem.
